In [3]:
import pandas as pd  
import numpy as np
from datetime import datetime, timedelta

In [7]:
data = pd.read_pickle("cell_profile_with_typhoon.pkl")
data

,Latitude,Longitude,wind_speed,mean_wind_speed,wind_cf,mean_wind_cf,solar_cf,mean_solar_cf,Province,Zone,...,wind_offshore_float_cap,solar_utility_cap,solar_rooftop_cap,fpv_reservoir_area_km2,fpv_natural_area_km2,solar_floating_area,solar_floating_cap,agri_voltaics_area,agri_voltaics_cap,wind_speed_typhoon
0,23.250,104.75,"[1.4134076400905697, 1.2765993152098343, 1.546...",2.673054,"[0.0, 0.0, 0.0, 0.0, 0.0003230612164566598, 0....",0.027587,"[0.040999999999999995, 0.151, 0.268, 0.3798, 0...",0.169459,Ha_Giang,1,...,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,0.000000,0.00000,"[1.4134076400905697, 1.2765993152098343, 1.546..."
1,23.250,105.00,"[1.161600714490837, 1.0395898467071756, 1.1486...",2.324091,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.00481367...",0.016864,"[0.0434, 0.15360000000000001, 0.2646, 0.3694, ...",0.166033,Ha_Giang,1,...,0.0,34.1535,9.1854,0.0,0.0,0.0,0.0,0.119625,3.58875,"[1.161600714490837, 1.0395898467071756, 1.1486..."
2,23.250,105.25,"[1.2220610882332317, 1.033450577598655, 1.0427...",2.280811,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.014128,"[0.0482, 0.16160000000000002, 0.2672, 0.358199...",0.165412,Ha_Giang,1,...,0.0,122.8776,49.4973,0.0,0.0,0.0,0.0,0.785800,23.57400,"[1.2220610882332317, 1.033450577598655, 1.0427..."
3,23.250,105.50,"[2.169471852722621, 1.740391518921886, 1.62100...",2.622165,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.000...",0.026811,"[0.0538, 0.17040000000000002, 0.27080000000000...",0.164791,Ha_Giang,1,...,0.0,48.7584,27.9603,0.0,0.0,0.0,0.0,0.208800,6.26400,"[2.169471852722621, 1.740391518921886, 1.62100..."
4,23.000,104.75,"[1.092397111469593, 0.9974153493701152, 1.2421...",2.037593,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.00638003...",0.007325,"[0.0374, 0.13520000000000001, 0.2412, 0.3442, ...",0.165374,Ha_Giang,1,...,0.0,19.0059,6.7239,0.0,0.0,0.0,0.0,0.050725,1.52175,"[1.092397111469593, 0.9974153493701152, 1.2421..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6970,8.550,105.15,"[10.480575988725922, 10.624011656339201, 11.55...",6.193723,"[0.9824707343803352, 0.9868193528841862, 0.999...",NaN,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.000000,Ca_Mau,6,...,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,0.000000,0.00000,"[10.480575988725922, 10.624011656339201, 11.55..."
6971,8.575,105.15,"[10.204901616888836, 10.274631049183135, 11.24...",6.134021,"[0.966849186963593, 0.9708005212747459, 0.9980...",NaN,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.000000,Ca_Mau,6,...,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,0.000000,0.00000,"[10.204901616888836, 10.274631049183135, 11.24..."
6972,8.600,105.15,"[9.927605282952223, 9.924497087382981, 10.9339...",6.070190,"[0.9469988872106794, 0.9466451447162222, 0.994...",NaN,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.000000,Ca_Mau,6,...,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,0.000000,0.00000,"[9.927605282952223, 9.924497087382981, 10.9339..."
6973,8.625,105.15,"[9.648147793639797, 9.573244306449926, 10.6259...",6.003069,"[0.9151939633202485, 0.9066692328949127, 0.986...",NaN,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.000000,Ca_Mau,6,...,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,0.000000,0.00000,"[9.648147793639797, 9.573244306449926, 10.6259..."
6974,8.650,105.15,"[9.372584327606013, 9.22853887982522, 10.32644...",5.934042,"[0.8774007583282161, 0.8537361488493019, 0.973...",NaN,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.000000,Ca_Mau,6,...,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,0.000000,0.00000,"[9.372584327606013, 9.22853887982522, 10.32644..."

In [8]:

highest_cap_cell = data.loc[data['wind_offshore_fixed_cap'].idxmax()]
print(highest_cap_cell)

wind_speeds = highest_cap_cell['wind_speed_typhoon']  

dates = []
start_year = 2002
end_year = 2021
for year in range(start_year, end_year + 1):
    start_date = datetime(year, 1, 1)
    for hour in range(8760):
        current_date = start_date + timedelta(hours=hour)
        if current_date.year == year: 
            dates.append(current_date.strftime("%m/%d/%y %H:%M"))

all_wind_speeds = np.tile(wind_speeds, end_year - start_year + 1)

result_df = pd.DataFrame({
    'datetime': dates,
    'windspeed': all_wind_speeds
})
result_df.head()

Latitude                                                                   8.75
Longitude                                                                 107.5
wind_speed                    [15.582406682361961, 15.841217130250008, 15.92...
mean_wind_speed                                                        8.172228
wind_cf                       [0.9813775019576227, 0.9789038812890999, 0.977...
mean_wind_cf                                                           0.548688
solar_cf                      [0.187, 0.3362, 0.46419999999999995, 0.5568, 0...
mean_solar_cf                                                          0.147422
Province                                                               Tra_Vinh
Zone                                                                          6
Landtype                                                                    1.0
C_ID                                                                       1179
Meso                                                                          0
M_ID                                                                          0
dist_to_coast_km                                                            NaN
Nearshore                                                                     0
landtype_areas_solar          {"Water Bodies": 0.0, "Built-up": 0.0, "Solar ...
landtype_areas_wind           {"Water Bodies": 0.0, "Built-up": 0.0, "Solar ...
landtype_areas_rooftop        {"Water Bodies": 0.0, "Built-up": 0.0, "Solar ...
total_feasible_solar_km2                                                    0.0
total_feasible_wind_km2                                                     0.0
total_feasible_rooftop_km2                                                  0.0
In_Vietnam                                                                  0.0
GM_area                                                                     0.0
RT_area                                                                     0.0
W_area                                                                      0.0
NW_area                                                                     0.0
fixed_OW_area                                                        761.100136
floating_OW_area                                                            0.0
wind_onshore_cap                                                            0.0
wind_nearshore_cap                                                          0.0
wind_offshore_fixed_cap                                             3044.400543
wind_offshore_float_cap                                                     0.0
solar_utility_cap                                                           0.0
solar_rooftop_cap                                                           0.0
fpv_reservoir_area_km2                                                      0.0
fpv_natural_area_km2                                                        0.0
solar_floating_area                                                         0.0
solar_floating_cap                                                          0.0
agri_voltaics_area                                                          0.0
agri_voltaics_cap                                                           0.0
wind_speed_typhoon            [15.582406682361961, 15.841217130250008, 15.92...
Name: 1178, dtype: object

         datetime  windspeed
0  01/01/02 00:00  15.582407
1  01/01/02 01:00  15.841217
2  01/01/02 02:00  15.924000
3  01/01/02 03:00  15.784434
4  01/01/02 04:00  15.414575

In [9]:
result_df.to_csv("library/weather/weather.csv", index=False)